In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from glob import glob
import math 
import sys

In [6]:
writer_director = pd.read_csv('rt_movie_clean.csv')
movie_budgets = pd.read_csv('movie_budgets_clean.csv')

In [8]:
writer_director.head()

,Unnamed: 0,id,synopsis,rating,genre,director,writer,theater_date
0,0,1,"This gritty, fast-paced, and innovative police...",R,Action and Adventure|Classics|Drama,William Friedkin,Ernest Tidyman,"Oct 9, 1971"
1,1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,"Aug 17, 2012"
2,2,5,Illeana Douglas delivers a superb performance ...,R,Drama|Musical and Performing Arts,Allison Anders,Allison Anders,"Sep 13, 1996"
3,3,6,Michael Douglas runs afoul of a treacherous su...,R,Drama|Mystery and Suspense,Barry Levinson,Paul Attanasio|Michael Crichton,"Dec 9, 1994"
4,5,8,The year is 1942. As the Allies unite overseas...,PG,Drama|Kids and Family,Jay Russell,Gail Gilchriest,"Mar 3, 2000"

In [9]:
movie_budgets.head()

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
0,1,"Dec 18, 2009",Avatar,425000000,760507625,2776345279
1,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,410600000,241063875,1045663875
2,3,"Jun 7, 2019",Dark Phoenix,350000000,42762350,149762350
3,4,"May 1, 2015",Avengers: Age of Ultron,330600000,459005868,1403013963
4,5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,317000000,620181382,1316721747

In [10]:
writer_director_roi = writer_director.merge(movie_budgets, left_on='theater_date', right_on='release_date', how='inner')

In [12]:
writer_director_roi.head()

,Unnamed: 0,id_x,synopsis,rating,genre,director,writer,theater_date,id_y,release_date,movie,production_budget,domestic_gross,worldwide_gross
0,0,1,"This gritty, fast-paced, and innovative police...",R,Action and Adventure|Classics|Drama,William Friedkin,Ernest Tidyman,"Oct 9, 1971",71,"Oct 9, 1971",The French Connection,2200000,41158757,41158757
1,1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,"Aug 17, 2012",81,"Aug 17, 2012",The Expendables 2,100000000,85028192,311979256
2,1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,"Aug 17, 2012",89,"Aug 17, 2012",ParaNorman,60000000,56003051,108119662
3,1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,"Aug 17, 2012",96,"Aug 17, 2012",Sparkle,10000000,24397469,24660323
4,1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,"Aug 17, 2012",4,"Aug 17, 2012",The Awakening,4900000,95933,6924321

In [14]:
writer_director_roi['roi'] = (writer_director_roi['worldwide_gross']/writer_director_roi['production_budget']) -1

In [15]:
writer_director_roi.head()

,Unnamed: 0,id_x,synopsis,rating,genre,director,writer,theater_date,id_y,release_date,movie,production_budget,domestic_gross,worldwide_gross,roi
0,0,1,"This gritty, fast-paced, and innovative police...",R,Action and Adventure|Classics|Drama,William Friedkin,Ernest Tidyman,"Oct 9, 1971",71,"Oct 9, 1971",The French Connection,2200000,41158757,41158757,17.708526
1,1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,"Aug 17, 2012",81,"Aug 17, 2012",The Expendables 2,100000000,85028192,311979256,2.119793
2,1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,"Aug 17, 2012",89,"Aug 17, 2012",ParaNorman,60000000,56003051,108119662,0.801994
3,1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,"Aug 17, 2012",96,"Aug 17, 2012",Sparkle,10000000,24397469,24660323,1.466032
4,1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,"Aug 17, 2012",4,"Aug 17, 2012",The Awakening,4900000,95933,6924321,0.413127